add custom side validation and index on database #29
chrisjamiecarter/habit-tracker-mvc pull request #30
Opened 2024-09-10 18:41 UTC by Pantex9

add custom side validation and index on database #29

2024-09-10 18:43 UTC, Pantex9 commented
I have implemented server-side validation for improved security and reliability. 
Additionally, to enhance user experience, I replaced error page redirections with toaster notifications, providing real-time feedback. 
Also, I optimized the Habit table by adding an index on the Name column to improve query performance.

2024-09-10 19:40 UTC, chrisjamiecarter requested changes
Hey @Pantex9,

I appreciate the effort! Some very nice improvements here!

I am going to add some comments to the changed files. Please could you action these.

Also, I love the toasts, the the issue was aiming to add validation.
If you see this page: https://stackoverflow.com/a/71059018
I was expecting to see a Validators folder and a UniqueNameAttribute.cs file created for this issue.

So that on a duplicate Habit Name you would see this:
![image](https://github.com/user-attachments/assets/e66f908a-e691-44e5-9f53-bddf4c9521c3)

Let me know if you have any issues.

Thanks,
@chrisjamiecarter

2024-09-10 19:44 UTC, chrisjamiecarter requested changes
Please see added comments

2024-09-10 19:44 UTC, chrisjamiecarter commented on src/HabitTracker.Domain/Helpers/ResponsePackage.cs
> +    public ResponsePackage()
See code style throughout the solution.
There should be whitespace between the regions and methods.
But not between regions.

2024-09-10 19:44 UTC, chrisjamiecarter commented on src/HabitTracker.Domain/Helpers/ResponsePackage.cs
> +
See above

2024-09-10 19:44 UTC, chrisjamiecarter commented on src/HabitTracker.Domain/Helpers/ResponsePackage.cs
> +    #endregion
See above

2024-09-10 19:44 UTC, chrisjamiecarter commented on src/HabitTracker.Infrastructure/Queries/TableQueries.cs
> +        CREATE INDEX IF NOT EXISTS IX_Habit_HabitName ON Habit(Name);
Small issue. Index should be IX_{Table}_{Column}, so expecting: IX_Habit_Name

2024-09-10 19:45 UTC, Pantex9 commented
Okay, I'll do that

2024-09-10 21:29 UTC, Pantex9 commented
Hi, I resolved the bugs from your comment. also, I align unique name validation attributes with add and update habits.
So when updating but not changing the name, the name can't fail validation, because this is the same name, not changed, but when we update the habit and change the name, then our system will check name from database.

2024-09-11 08:17 UTC, chrisjamiecarter requested changes
Hey @Pantex9 ,

Great work! This looks like it will close the issue.

Just one more update...

I've made the infrastructure classes internal to maintain clean architecture principles. This ensures:
- Encapsulation: Infrastructure is only accessible within its own project, keeping the core business logic isolated.
- Maintainability: It prevents accidental use of infrastructure details outside its layer, making future changes easier.
- Reduced Coupling: The core application depends on abstractions, not concrete implementations, promoting flexibility.

It is important in source control that you only work on the issue at hand and not try refactor / change too much stuff out of scope.

Please revert back to internal and let me know if you have any questions!

Thanks
@chrisjamiecarter

2024-09-11 09:38 UTC, Pantex9 commented
Hey @chrisjamiecarter, 
sorry about that, I tried something and forgot to revert this.
I revert it now

2024-09-11 12:20 UTC, chrisjamiecarter approved these changes
@Pantex9 

Fantastic work!

I have approved, and will merge the pull request.

closes #30

2024-09-11 13:48 UTC, merged